### ISSUE TITLE
Error changing password

### ISSUE THREAD

**Issue by gaborszita** [Eaglestrike/Eaglescout-2022#9]
When I try to change my password, I get this error:

```
TypeError: req.checkBody is not a function
    at /var/www/scout/routes/account.js:14:6
    at Layer.handle [as handle_request] (/var/www/scout/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/scout/node_modules/express/lib/router/route.js:137:13)
    at ensureAuthenticated (/var/www/scout/utils.js:6:11)
    at Layer.handle [as handle_request] (/var/www/scout/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/scout/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/scout/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/scout/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/scout/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/www/scout/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/scout/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/var/www/scout/node_modules/express/lib/router/index.js:174:3)
    at router (/var/www/scout/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/var/www/scout/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/scout/node_modules/express/lib/router/index.js:317:13)
    at /var/www/scout/node_modules/express/lib/router/index.js:284:7
```

**Steps to reproduce:**
1. Click on "Account" on the dashboard.
2. Enter values for the fields if you want to, it fails anyways.
3. Click change password. You will get the error above.

btw I do not need to change my password, that's not why I'm writing this, I was just testing if it works. And I found out it doesn't.

**Comment by Versus7** [comment]
It looks like your latest PR fixed this, although for context we've seen this error before with our outdated express-validator code. If you go back many commits you'll see we encountered this, and only updated the code that was actively causing errors.

**Comment by gaborszita** [comment]
> It looks like your latest PR fixed this, although for context we've seen this error before with our outdated express-validator code. If you go back many commits you'll see we encountered this, and only updated the code that was actively causing errors.

Yeah, I know, I mentioned this in the PR #10 :

![image](https://user-images.githubusercontent.com/30361931/202628555-d39db9c5-0976-4505-842c-032621de7ca9.png)
